;; -*- lexical-binding: t -*-
(add-to-list 'load-path "~/.emacs.d/elisp/")

(require 'basic-conf)
(require 'editing-conf)
(require 'theme-conf)
(require 'key-conf)
(require 'completion-conf)
(require 'org-conf)
(require 'lang-conf)
(require 'git-conf)
(require 'eshell-conf)
(require 'dired-conf)
(require 'tab-conf)
(require 'window-conf)
(require 'note-conf)
